### ISSUE TITLE
`.AddGitHubWebHooks();` custom secret value

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/AspLabs#36] opened 2018-10-17 18:51 UTC
_From @MartinDawson on Saturday, October 6, 2018 11:30:43 AM_

`.AddGitHubWebHooks();` seems to internally use `appsettings.json`.

It would be nice to get the value directly myself and pass it in as a parameter because I don't want to use `appsettings.json`.

Thanks!

_Copied from original issue: aspnet/WebHooks#326_

**Comment by dougbu** [comment] 2018-11-01 22:30
ASP.NET Core WebHooks uses `IConfiguration` to retrieve properties such as secret keys. Any input source configured for `IConfiguration` works, not just `appsettings.json` files e.g. command-line options and environment variables. What is missing exactly?

**Comment by dougbu** [comment] 2018-11-27 22:56
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-11-27 22:56 UTC
Labels: area-WebHooks
