### ISSUE TITLE
SalesForce WebHook Issue with ASP.Net Core 3

### ISSUE THREAD

**Issue by MarkBQE** [aspnet/AspLabs#231] opened 2019-10-24 03:48 UTC
I get the following error  when posting to a salesforce webhook receiver in ASPNET Core 3. Salesforce webhook  works flawlessly with Asp.net core 2. I am using the following link for reference

https://devblogs.microsoft.com/aspnet/integrating-with-salesforce-using-asp-net-webhooks-preview/

System.NotSupportedException: Specified method is not supported.
   at Microsoft.AspNetCore.Server.IIS.Core.ReadOnlyStream.Seek(Int64 offset, SeekOrigin origin)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Seek(Int64 offset, SeekOrigin origin)
   at Microsoft.AspNetCore.WebHooks.Internal.WebHookRequestReader.ReadBodyAsync[TModel](ActionContext actionContext)
   at Microsoft.AspNetCore.WebHooks.Filters.SalesforceVerifyOrganizationIdFilter.OnResourceExecutionAsync(ResourceExecutingContext context, ResourceExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept-Encoding: gzip
Content-Length: 1709
Content-Type: text/xml; charset=utf-8
Host: localhost:44370
User-Agent: Jakarta Commons-HttpClient/3.1
Soapaction: ""
X-Forwarded-For: 13.108.238.8
X-Forwarded-Proto: https
X-Original-Host: 94c3bf76.ngrok.io

**Comment by mguinness** [comment] 2019-11-15 19:48
The underlying code looks like it's trying to rewind the stream to the beginning.  Not sure why this behavior would be different in ASPNET Core 3.

https://github.com/aspnet/AspLabs/blob/35541c8e34559103f73ddbb44b4fa323b65885e3/src/WebHooks/src/Microsoft.AspNetCore.WebHooks.Receivers/WebHookRequestReader.cs#L106-L114

**Comment by MarkBQE** [comment] 2020-05-02 08:18
Content-Type Header is

Content-Type | text/xml; charset=utf-8

**Comment by mguinness** [comment] 2020-05-02 19:50
Have you tried the latest 3.1 release?  It seems like there was a regression with [EnableBuffering not working on .Net Core 3.0.100](https://github.com/dotnet/aspnetcore/issues/14396) causing issues.

**Comment by MarkBQE** [comment] 2020-05-04 07:31
This piece of code in the middle ware pipeline worked for me. thanks for this tip

app.Use(next => context =>
		{
			var syncIOFeature = context.Features.Get<IHttpBodyControlFeature>();
			if (syncIOFeature != null)
			{
				syncIOFeature.AllowSynchronousIO = true;
			}

			context.Request.EnableBuffering();
			return next(context);
		});

**Comment by mguinness** [comment] 2020-05-04 16:49
Awesome, thanks for sharing your workaround.

**Comment by mkArtakMSFT** [comment] 2020-08-28 19:42
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.

**Closed by mkArtakMSFT** 2020-08-28 19:42 UTC
